spring:
  application:
    name: project-ms-one-credit
  data:
    mongodb:
      uri: mongodb+srv://dvivasva:admin23@everis.xiybt.mongodb.net/project-one

  cloud:
    config:
      enabled: false
server:
  port: 8089
